
=head1 OPTIONS

=head2 Common Job Configuration Options

You will probably specify all of these options for any given job.

=over 4

=item B<FORWARD> (required)

=item B<REVERSE> (optional)

For unpaired data, the single file of reads.  For paired data the
files of forward and reverse reads. Files can be either fasta or
fastq; the type is inferred.

=head2 BLAT options

You can tweak the BLAT portion of RUM to suit your needs. We found the
following to be a good balance for speed, sensitivity, and temporary
file size. Like the other settings above, these values are saved in a
file in the output directory so you don't need to enter them twice,
and you should not change them once you start a job.

=over 4

=back

=head2 Directives

These options are not saved as part of the configuration file, and
only affect how RUM behaves on one invocation. If you want to manually
split up job into chunks and run each chunk separately, you can use
the I<--preprocessing>, I<--processing>, I<--postprocessing>, and
I<--chunks> options to do that. Detailed instructions on doing that are
provided L<here|https://github.com/PGFI/rum/wiki/Running-a-job-on-a-cluster>.

=over 4

=item B<--preprocessing>

=item B<--processing>

=item B<--postprocessing>

The RUM pipeline can be broken into three distinct phases:
preprocessing (splitting the input files into chunks), processing
(mapping the reads for each chunk, possibly distributed), and
postprocessing (merging the results together). By default rum_runner
will run any outstanding steps in all three phases, but you can tell
it to run just one of the phases by supplying the corresponding
option.

=back

=head1 LOGO

  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  RUM version: $version
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   _   _   _   _   _   _
                 // \\// \\// \\// \\// \\// \\/
                //\\_//\\_//\\_//\\_//\\_//\\_//
          o_O__O_ o
         | ====== |       .-----------.
         `--------'       |||||||||||||
          || ~~ ||        |-----------|
          || ~~ ||        | .-------. |
          ||----||        ! | UPENN | !
         //      \\        \`-------'/
        // /!  !\ \\        \_  O  _/
       !!__________!!         \   /
       ||  ~~~~~~  ||          `-'
       || _        ||
       |||_|| ||\/|||
       ||| \|_||  |||
       ||          ||
       ||  ~~~~~~  ||
       ||__________||
  .----|||        |||------------------.
       ||\\      //||                 /|
       |============|                //
       `------------'               //
  ---------------------------------'/
  ---------------------------------'
    .------------------------------------.
    | RNA-Seq Unified Mapper (RUM) Usage |
    ` ================================== '

=cut

=head1 SEE ALSO

L<rum_runner>

=head1 AUTHORS

Gregory Grant (ggrant@grant.org)

Mike DeLaurentis (delaurentis@gmail.com)

=head1 COPYRIGHT

Copyright 2012, University of Pennsylvania

