=head1 NAME

rum_runner stop - Stop a job.

=head1 SYNOPSIS

rum_runner kill -o dir

=head1 DESCRIPTION

Stop a job, leaving all output files intact. Note that if you're
running a job locally (not on a cluster) you should be able to stop it
with CTRL-C.

=head1 OPTIONS

=over 4

=item B<-o>, B<--output> I<dir>

Specify the output directory of the job. 

=back

=head1 SEE ALSO

L<rum_runner>

=head1 AUTHORS

Gregory Grant (ggrant@grant.org)

Mike DeLaurentis (delaurentis@gmail.com)

=head1 COPYRIGHT

Copyright 2012, University of Pennsylvania

=cut
