(defun rum-pod-footer ()
  "Inserts standard pod footer"
  (interactive)
  (insert "=head1 AUTHOR\n\n")
  (insert "Mike DeLaurentis (delaurentis@gmail.com)\n\n")
  (insert "=head1 COPYRIGHT\n\n")
  (insert "Copyright 2012 University of Pennsylvania\n\n")
  (insert "=cut"))

(defun rum-pod-method (name)
  "Inserts pod for method"
  (interactive "sMethod name: \n")
  (insert "=item " name "\n\n\n\n=cut\n\n")
  (backward-to-indentation 4))

(defun rum-pod-header (name desc)
  (interactive "sPackage name: \nsDescription")
  (insert "=head1 NAME\n\n" name " - " desc "\n\n=head1 SYNOPSIS\n\n\n\n=head1 DESCRIPTION\n\n\n\n=cut\n\n")
  (backward-to-indentation 8))

(defun rum-pod-option (short long arg desc)
  (interactive "sShort name: \nsLong name: \nsArgument: \nsDescription: ")
  (insert "=item ")
  (unless (string= "" short)
    (insert "B<-" short ">"))
  (unless (or (string= "" short)
              (string= "" long))
    (insert ", "))
  (unless (string= "" long)
    (insert "B<--" long ">"))
  (unless (string= "" arg)
    (insert " I<" arg ">"))
  (insert "\n\n")
  (unless (string= "" desc)
    (insert desc "\n\n")))

(defun rum-pod-standard-options ()
  (interactive)
  (rum-pod-option "h" "help" "" "")
  (rum-pod-option "v" "verbose" "" "")
  (rum-pod-option "q" "quiet" "" ""))

(defun rum-new-script-package (package)
  (interactive "sPackage: \n")
  
  (find-file (format "~/src/rum/lib/RUM/Script/%s.pm" package))
  (insert "package RUM::Script::" package ";\n")
  (insert "\n")
  (insert "no warnings;\n")
  (insert "use RUM::Usage;\n")
  (insert "use RUM::Logging;\n")
  (insert "use Getopt::Long;\n")
  (insert "\n")
  (insert "our $log = RUM::Logging->get_logger();\n")
  (insert "\n")
  (insert "sub main {\n")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "}\n")
  (insert "\n")
  (insert "1;\n")
  (backward-to-indentation 5))